version: "3"
vars:
  SOURCE: '{{ .SOURCE | default "Anarchist Library.js" }}'
  SOURCE_FILE: '{{ base .SOURCE }}'
  DEST: "${HOME}/Zotero/translators/{{ .SOURCE }}"
tasks:
  install:
    cmd: install -m 0644 '{{ .SOURCE }}' "{{ .DEST }}"
  fetch:
    cmd: cp "{{ .DEST }}" "{{ .SOURCE }}-fetched"
  push-upstream:
    preconditions:
      - sh: git diff --quiet -- ":(exclude)Taskfile.yml"
        msg: No local changes before pushing!
    vars:
      UPSTREAM_REPO: '{{ .UPSTREAM_REPO | default .CLI_ARGS | default "../translators" }}'
      REMOTE: '{{ .UPSTREAM_REMOTE | default "origin" }}'
      THIS_BRANCH:
        sh: git branch --show-current
      TARGET_FILE: '{{ .UPSTREAM_REPO }}/{{ .SOURCE_FILE }}'
      TARGET_BRANCH_FROM_FILE:
        sh: |
          if test -x '.target_branch'; then
            ./.target_branch
          elif test -f .target_branch; then
            cat .target_branch
          fi
      DEFAULT_TARGET_BRANCH:
        sh: >
          test -n '{{ .TARGET_BRANCH_FROM_FILE }}' 
          && echo -n '{{ .TARGET_BRANCH_FROM_FILE }}'
          || echo -n '{{ .THIS_BRANCH }}'
      TARGET_BRANCH: '{{ .TARGET_BRANCH | default .DEFAULT_TARGET_BRANCH }}'
      SOURCE_COMMIT:
        sh: git rev-parse --short HEAD
      COMMIT_MSG_BASE:
        sh: >
          test -f '{{ .TARGET_FILE }}' && echo "Adding new translator {{ .SOURCE_FILE }}"
          || echo "Updating translator {{ .SOURCE_FILE }}" 
      COMMIT_MSG: '{{.COMMIT_MSG_BASE}} from {{ .THIS_BRANCH }} {{ .SOURCE_COMMIT }}'
    cmds:
      - install -m 0644 '{{ .SOURCE }}' '{{ .TARGET_FILE }}'
      - |
        cd {{ .UPSTREAM_REPO }}
        current_branch="$(git branch --show-current)"
        git rev-parse '{{ .TARGET_BRANCH }}' && git checkout '{{ .TARGET_BRANCH }}' || exit "branch {{ .TARGET_BRANCH }} does not exist"
        git add '{{ .SOURCE_FILE }}'
        git commit -m '{{ .COMMIT_MSG }}' && git push -u {{ .REMOTE }} {{ .TARGET_BRANCH }}