version: "3"
vars:
  SOURCE: '{{ .SOURCE | default "Anarchist Library.js" }}'
  SOURCE_FILE: '{{ base .SOURCE }}'
  DEST: "${HOME}/Zotero/translators/{{ .SOURCE }}"
  UPSTREAM_REPO: '{{ .UPSTREAM_REPO | default .CLI_ARGS | default "../translators" }}'
  REMOTE: '{{ .UPSTREAM_REMOTE | default "origin" }}'
  THIS_BRANCH:
    sh: git branch --show-current
  TARGET_FILE: '{{ .UPSTREAM_REPO }}/{{ .SOURCE_FILE }}'
  TARGET_BRANCH_FROM_FILE:
    sh: |
      if test -x '.target_branch'; then
        ./.target_branch
      elif test -f .target_branch; then
        cat .target_branch
      fi
  DEFAULT_TARGET_BRANCH:
    sh: >
      test -n '{{ .TARGET_BRANCH_FROM_FILE }}'
      && echo -n '{{ .TARGET_BRANCH_FROM_FILE }}'
      || echo -n '{{ .THIS_BRANCH }}'
  TARGET_BRANCH: '{{ .TARGET_BRANCH | default .DEFAULT_TARGET_BRANCH }}'
tasks:
  clean:
    cmd: rm -rf .ci/pull-request-check/connectors
  install:
    cmd: install -m 0644 '{{ .SOURCE }}' "{{ .DEST }}"
  fetch:
    cmd: cp "{{ .DEST }}" "{{ .SOURCE }}-fetched"
  compare-upstream:
    cmds:
      - diff '{{ .TARGET_FILE }}' '{{ .SOURCE_FILE }}'
  install-upstream:
    cmds:
      - install -m 0644 '{{ .SOURCE }}' '{{ .TARGET_FILE }}'

  push-upstream:
    preconditions:
      - sh: git diff --quiet -- ":(exclude)Taskfile.yml"
        msg: No local changes before pushing!
    deps:
      - install-upstream
    vars:
      SOURCE_COMMIT:
        sh: git rev-parse --short HEAD
      COMMIT_MSG_BASE:
        sh: >
          test -f '{{ .TARGET_FILE }}' && echo "Updating translator {{ .SOURCE_FILE }}"
          || echo "Adding new translator {{ .SOURCE_FILE }}"
      # TODO: Add source repo (remote origin) info to this
      COMMIT_MSG: '{{.COMMIT_MSG_BASE}} from {{ .THIS_BRANCH }} {{ .SOURCE_COMMIT }}'
      CREATE_MISSING_BRANCH: '{{ .CREATE_MISSING_BRANCH | default "YES" }}'
      doesnt_exist_error: sh -c 'echo "branch {{ .TARGET_BRANCH }} does not exist" && exit 13'
      checkout_new_branch: git checkout -b '{{.TARGET_BRANCH}}'
      IF_MISSING_BRANCH: '{{ if eq .CREATE_MISSING_BRANCH "YES" }}{{ .checkout_new_branch }}{{ else }}{{ .doesnt_exist_error }}{{ end }}'
    cmds:
      - |
        cd {{ .UPSTREAM_REPO }}
        current_branch="$(git branch --show-current)"
        git rev-parse '{{ .TARGET_BRANCH }}' && git checkout '{{ .TARGET_BRANCH }}' || {{ .IF_MISSING_BRANCH }}
        git add '{{ .SOURCE_FILE }}'
        git commit -m '{{ .COMMIT_MSG }}' && git push -u {{ .REMOTE }} {{ .TARGET_BRANCH }}
  lint:
    dir: .ci
    cmds:
      - ./lint.sh
  lint-fix:
    dir: .ci
    cmds:
      - ./lint.sh -- --fix
  ci-check:
    dir: ".ci/pull-request-check"
    cmds:
      - ./check-pull-request.sh
